# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodb:/data/db
    ports:
      - 8518:27017
  server:
    build: 
      context: ./
      dockerfile: ServerDockerfile
    image: hpstats_server
    ports:
      - 8519:8519
    volumes:
      - ./:/usr/src/
    links:
      - 'mongo'